#pragma once

#define STR_HELPER(x) #x
#define STR(x) STR_HELPER(x)

#define BHAS_MAJOR_VERSION 0
#define BHAS_MINOR_VERSION 7
#define BHAS_PATCH_VERSION 0

#define BHAS_VERSION_LABEL "viper"

#define BHAS_FIRMWARE_VERSION "v" STR(BHAS_MAJOR_VERSION) "." STR(BHAS_MINOR_VERSION) "." STR(BHAS_PATCH_VERSION) "-" BHAS_VERSION_LABEL